name: Build Windows Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Type check (allow failures)
      run: npm run type-check || echo "TypeScript errors ignored"
      continue-on-error: true
    
    - name: Build Vue app
      run: npm run build-only
    
    - name: Build Electron app for Windows
      run: npm run electron:build-win
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: release/*.exe

  release:
    needs: build-windows
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download Windows artifacts
      uses: actions/download-artifact@v4
      with:
        name: windows-build
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: windows-build/*
        draft: false
        prerelease: false
        body: |
          ## Nouvelle version Windows
          
          Cette version contient uniquement l'exécutable Windows (.exe).
          
          ### Installation
          1. Téléchargez le fichier .exe
          2. Exécutez l'installateur
          3. Suivez les instructions d'installation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}